spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:mysql://localhost:3306/library_management_system
    username: dev
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /my/docs
jwt:
  secret: p2s5u8x/A?D(G+KbPeShVmYq3t6w9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgp2s5u8x/A?D(G+KbPeShVmYq3t6w9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRg
  expiry: 60

