package in.geekster.springdatajpademo.enums;

public enum Designation {

    QA, SENIOR_QA, SE, SSE, ARCHITECT, SENIOR_ARCHITECT, ASSOCIATE_MARKETER, MARKETING_MANAGER, ASSOCIATE_BUSINESS_DEVELOPER, SENIOR_BUSINESS_DEVELOPER, HR
}
